name: Build Redmi K60 Pro Kernel Engine

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # 手动触发选项

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            bc \
            bison \
            flex \
            libssl-dev \
            libncurses5-dev \
            curl \
            libelf-dev \
            ccache \
            git-core \
            gnupg2 \
            wget \
            python3 \
            rsync \
            zip \
            device-tree-compiler \
            gcc-aarch64-linux-gnu \
            liblz4-dev \
            libzstd-dev \
            libxml2-utils \
            make \
            libudev-dev \
            libpci-dev \
            dwarves  # pahole 工具

      - name: Download specific Clang version (r450784e)
        run: |
          git clone https://github.com/snove520/clang-r450784e.git
          chmod 777 -R $PWD/clang-r450784e
          export PATH="$PWD/clang-r450784e/bin:$PATH"

      - name: Download MiLinuxKernel source
        run: |
          git clone --depth=1 -b MiEngine_1 https://github.com/3582730951/MiLinuxKernel_4.git
          cd MiLinuxKernel_4

      - name: Configure the kernel with migki_defconfig
        run: |
          chmod 777 -R MiLinuxKernel_4
          cd MiLinuxKernel_4
          ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- make migki_defconfig

      - name: Build the kernel
        run: |
          cd MiLinuxKernel_4
          ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- make -j$(nproc)

      - name: Upload kernel build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: redmi-k60pro-gki-kernel
          path: MiLinuxKernel_4/arch/arm64/boot/Image*
