name: Build Kernel with Bazel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # 手动触发选项

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            bc \
            bison \
            flex \
            libssl-dev \
            libncurses5-dev \
            curl \
            libelf-dev \
            ccache \
            git-core \
            gnupg2 \
            wget \
            python3 \
            rsync \
            zip \
            device-tree-compiler \
            gcc-aarch64-linux-gnu \
            clang-14 \
            lld-14 \
            llvm-14 \
            liblz4-dev \
            libzstd-dev \
            libxml2-utils \
            make \
            libudev-dev \
            libpci-dev \
            dwarves \
            apt-transport-https \
            curl \
            gnupg

      - name: Add Bazel APT repository and install Bazel
        run: |
          curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor >bazel-archive-keyring.gpg
          sudo mv bazel-archive-keyring.gpg /usr/share/keyrings
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/bazel-archive-keyring.gpg] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
          sudo apt update && sudo apt install -y bazel
          sudo apt update && sudo apt full-upgrade

      - name: Download and extract clang
        run: |
          wget https://github.com/3582730951/MiLinuxKernel_4/releases/download/1/clang-r450784e-main.zip -O clang-r450784e-main.zip
          unzip clang-r450784e-main.zip -d clang

      - name: Set up Clang environment
        run: |
          export PATH=$PWD/clang/bin:$PATH
          export CC=$PWD/clang/bin/clang
          export CXX=$PWD/clang/bin/clang++
          export LLVM=1

      - name: Clone the kernel source
        run: |
          git clone --branch MiEngine_1 https://github.com/3582730951/MiLinuxKernel_4.git
          cd MiLinuxKernel_4

      - name: Build the kernel with Bazel
        run: |
          chmod -R 777 MiLinuxKernel_4
          cd MiLinuxKernel_4
          tools/bazel build //common:kernel_aarch64_dist

      - name: Upload kernel build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: kernel-artifacts
          path: MiLinuxKernel_4/common/arch/arm64/boot/*
