name: Build Kernel using Bazel (Kleaf)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # 手动触发选项

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            bc \
            bison \
            flex \
            libssl-dev \
            libncurses5-dev \
            curl \
            libelf-dev \
            ccache \
            git-core \
            gnupg2 \
            wget \
            python3 \
            rsync \
            zip \
            device-tree-compiler \
            gcc-aarch64-linux-gnu \
            clang-14 \
            lld-14 \
            llvm-14 \
            liblz4-dev \
            libzstd-dev \
            libxml2-utils \
            make \
            libudev-dev \
            libpci-dev \
            dwarves \
            python3-pip \
            unzip \
            libcurl4-openssl-dev

      - name: Checkout MiLinuxKernel_4 repository
        run: |
          git clone https://github.com/3582730951/MiLinuxKernel_4.git --branch MiEngine_1
          cd MiLinuxKernel_4

      - name: Download and extract clang toolchain
        run: |
          wget https://github.com/3582730951/MiLinuxKernel_4/releases/download/1/clang-r450784e-main.zip
          unzip clang-r450784e-main.zip
          # 添加 clang 工具链到路径
          export PATH=$PWD/clang-r450784e-main/bin:$PATH
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CC=clang
          export CXX=clang++

      - name: Install Bazel
        run: |
          sudo apt install apt-transport-https curl gnupg
          curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor >bazel-archive-keyring.gpg
          sudo mv bazel-archive-keyring.gpg /usr/share/keyrings
          sudo apt update && sudo apt install bazel-5.0.0
          sudo apt update && sudo apt full-upgrade
          sudo apt install bazel

      - name: Build the kernel using Bazel
        run: |
          chmod -R 777 MiLinuxKernel_4
          cd MiLinuxKernel_4
          tools/bazel build //common:kernel_aarch64_dist

      - name: Upload kernel build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mi-linux-kernel-boot-files
          path: MiLinuxKernel_4/common/arch/arm64/boot/**
