name: Build MiLinuxKernel_4 GKI Kernel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # 手动触发选项

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            bc \
            bison \
            flex \
            libssl-dev \
            libncurses5-dev \
            curl \
            libelf-dev \
            ccache \
            git-core \
            gnupg2 \
            wget \
            python3 \
            rsync \
            zip \
            device-tree-compiler \
            gcc-aarch64-linux-gnu \
            liblz4-dev \
            libzstd-dev \
            libxml2-utils \
            make \
            libudev-dev \
            libpci-dev \
            dwarves

      - name: Download MiLinuxKernel_4 source
        run: |
          git clone https://github.com/3582730951/MiLinuxKernel_4.git
          cd MiLinuxKernel_4
          git checkout MiEngine_1

      - name: Download Google clang r450784e
        run: |
          wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 -O clang-r450784e.tar.gz
          tar -xvf clang-r450784e.tar.gz -C /opt/clang-r450784e
          export PATH=/opt/clang-r450784e/bin:$PATH

      - name: Configure the kernel with migki_defconfig
        run: |
          cd MiLinuxKernel_4
          ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- make migki_defconfig

      - name: Build the kernel
        run: |
          cd MiLinuxKernel_4
          ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CC=clang LD=ld.lld make -j$(nproc)

      - name: Upload kernel build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: redmi-k60pro-gki-kernel
          path: MiLinuxKernel_4/arch/arm64/boot/Image*
